// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 Andrei Baranov (84softworks). Licensed under the Business Source License 1.1 - see LICENSE.
import { useState, type FormEvent } from 'react';
import { Alert, Button, Group, Modal, Stack, TextInput } from '@mantine/core';

import { describeApiError } from '@/api/baseQuery';
import { useIssueServiceTokenMutation } from '@/api/integrationApi';
import type { IssuedServiceToken } from '@/api/types';
import { useLang } from '@/i18n/LangContext';

interface IssueServiceTokenModalProps {
  opened: boolean;
  onClose: () => void;
  onIssued: (issued: IssuedServiceToken) => void;
}

/** A name is all a token needs; the value is generated by the server and shown once by the caller. */
export function IssueServiceTokenModal({ opened, onClose, onIssued }: IssueServiceTokenModalProps) {
  const { t } = useLang();
  const copy = t.integration.tokens.create;
  const [issueToken, { isLoading, error, reset }] = useIssueServiceTokenMutation();
  const [name, setName] = useState('');

  const close = () => {
    setName('');
    reset();
    onClose();
  };

  const submit = async (event: FormEvent) => {
    event.preventDefault();
    try {
      const issued = await issueToken({ name: name.trim() }).unwrap();
      close();
      onIssued(issued);
    } catch {
      // Rendered from the mutation state below
    }
  };

  return (
    <Modal opened={opened} onClose={close} title={copy.title}>
      <form onSubmit={submit}>
        <Stack gap="md">
          <TextInput
            label={copy.name}
            description={copy.nameHint}
            value={name}
            onChange={(event) => setName(event.currentTarget.value)}
            maxLength={48}
            required
            data-autofocus
          />
          {error && <Alert color="red">{describeApiError(error, t.api)}</Alert>}
          <Group justify="flex-end">
            <Button variant="default" onClick={close} disabled={isLoading}>
              {t.common.cancel}
            </Button>
            <Button type="submit" loading={isLoading}>
              {t.common.create}
            </Button>
          </Group>
        </Stack>
      </form>
    </Modal>
  );
}
